#!/usr/bin/env python

from sys import stdin,stdout,argv

def prn(msg=None):
	if msg is not None:
		stdout.write(msg)
	stdout.write('\n')

if len(argv) < 2:
	prn('error command format')
	exit(1)

prn()

def open_all_files():
	for f in argv[1:]:
		for line in open(f):
			yield line

last_valid_line = None
last_invalid = False
for line in open_all_files():
	line = line.strip()
	fields = line.split()
	fields_num = len(fields)
	if fields_num==4:
		last_valid_line = line
		if last_invalid:
			prn(line)
			prn()
		last_invalid = False
	elif fields_num==3:
		last_invalid = True
		if last_valid_line is not None:
			prn(last_valid_line)
			last_valid_line = None
		prn(line)

