#!/usr/bin/env python

def get_datarate(dimension):
	dim1,dim2,single_block_bits,freshrate = dimension
	return dim1 * dim2 * single_block_bits * freshrate

dimensions = [
	(1280, 720, 32, 60),
	(1366, 768, 32, 60),
	(1920, 1080, 32, 60),
	(2560, 1440, 32, 60),
	(3840, 2160, 32, 60),
	(1280, 720, 16, 30),
	(1366, 768, 16, 30),
	(1920, 1080, 16, 30),
	(2560, 1440, 16, 30),
	(3840, 2160, 16, 30)
]
print('\t'.join(['pixels1', 'pixels2', 'blkbits', 'frsrate', 'Mbps', 'MBps']))
for dimension in dimensions:
	datarate = get_datarate(dimension)
	fields = map(str, dimension)
	fields.append( '%.1f' % (datarate*1.0/1024/1024) )
	fields.append( '%.1f' % (datarate*1.0/1024/1024/8) )
	print('\t'.join(fields))

